Repository 6C-Solutions-4-Small-Businesses/online-shop-template, pull requests merged in 2024-07, with the labels that each got.

#43 style: Integrate design
  config/ScreenSizeConfig.ts
  package-lock.json
  package.json
  src/app.html
  src/lib/frontend/assets/images/market.webp
  src/lib/frontend/components/.Collection.svelte.swp
  src/lib/frontend/components/Collection.svelte
  src/lib/frontend/components/CookiesDisclaimerModal.svelte
  src/lib/frontend/components/CustomAppBar.svelte
  src/lib/frontend/components/ProductCard.svelte
  src/lib/frontend/components/SearchInput.svelte
  src/lib/frontend/components/ShoppingCartActions.svelte
  src/lib/frontend/components/SpotlightedProductCard.svelte
  src/routes/+layout.svelte
  src/routes/+page.svelte
  src/routes/cart/+page.svelte
  src/routes/cart/checkout/+page.svelte
  src/routes/terms-and-conditions/+page.svelte
  src/translations/en/lib/frontend/components/collection.json
  src/translations/en/lib/frontend/components/custom-app-bar.json
  src/translations/en/routes/layout.json
  src/translations/en/routes/page.json
  src/translations/fr/lib/frontend/components/collection.json
  src/translations/fr/lib/frontend/components/custom-app-bar.json
  src/translations/fr/routes/layout.json
  src/translations/fr/routes/page.json
  src/translations/fr/routes/terms-and-conditions/page.json
  src/translations/index.ts
  static/add-button.svg
  static/arrow-left.svg
  static/delivery.webp
  static/market.png
  static/remove-button.svg
  static/search.svg
  static/send.svg
  static/shopping-cart.svg
  static/user.svg
  static/vector.svg
  tailwind.config.ts
Labels: beautification

#53 enhancement: change shopping cart sub total and checkout layout
  src/routes/cart/+page.svelte
  tailwind.config.ts
  tests/unit/src/routes/cart/+page.svelte.spec.ts
  tests/unit/src/routes/cart/__snapshots__/+page.svelte.spec.ts.snap
Labels: good first issue, enhancement, beautification

#59 feat: change shopping cart page layout
  src/lib/frontend/components/ProductCard.svelte
  src/lib/frontend/components/ShoppingCartProductCard.svelte
  src/lib/frontend/components/SpotlightedProductCard.svelte
  src/lib/frontend/components/icons/SortIcon.svelte
  src/routes/cart/+page.svelte
  src/translations/en/routes/cart/page.json
  src/translations/fr/routes/cart/page.json
  src/translations/index.ts
  tailwind.config.ts
  tests/unit/src/lib/frontend/components/ShoppingCartActions.svelte.spec.ts
  tests/unit/src/lib/frontend/components/__snapshots__/Collection.spec.ts.snap
  tests/unit/src/lib/frontend/components/__snapshots__/ProductCard.spec.ts.snap
  tests/unit/src/lib/frontend/components/__snapshots__/ProductDataTable.spec.ts.snap
  tests/unit/src/lib/frontend/components/__snapshots__/ShoppingCartProductCard.spec.ts.snap
  tests/unit/src/routes/__snapshots__/HomePage.spec.ts.snap
  tests/unit/src/routes/cart/__snapshots__/+page.svelte.spec.ts.snap
  tests/unit/src/routes/category/[id]/__snapshots__/+page.svelte.spec.ts.snap
Labels: good first issue, enhancement, beautification

#63 feat: change products category page layout
  src/lib/frontend/components/CategoryProducts.svelte
  src/lib/frontend/components/Collection.svelte
  src/lib/frontend/components/ProductCardShadow.svelte
  src/lib/frontend/components/ProductCardSkeleton.svelte
  src/lib/frontend/components/ProductDataTable.svelte
  src/lib/frontend/components/TitleBox.svelte
  src/routes/cart/+page.svelte
  src/routes/category/[id]/+page.server.ts
  src/routes/category/[id]/+page.svelte
  src/routes/offer/search/+page.svelte
  src/translations/en/lib/frontend/components/category-products.json
  src/translations/en/routes/category/page.json
  src/translations/fr/lib/frontend/components/category-products.json
  src/translations/fr/routes/category/page.json
  src/translations/index.ts
  tests/unit/src/lib/frontend/components/CategoryProducts.spec.ts
  tests/unit/src/lib/frontend/components/__snapshots__/CategoryProducts.spec.ts.snap
  tests/unit/src/routes/category/[id]/+page.server.spec.ts
  tests/unit/src/routes/category/[id]/+page.svelte.spec.ts
  tests/unit/src/routes/category/[id]/__snapshots__/+page.svelte.spec.ts.snap
Labels: good first issue, enhancement, beautification

#68 bug(frontend): Restored lost Tailwin color classes
  src/lib/frontend/components/CustomAppBar.svelte
  src/lib/frontend/components/ProductCard.svelte
  src/lib/frontend/components/ShoppingCartActions.svelte
  src/lib/frontend/components/ShoppingCartProductCard.svelte
  tailwind.config.ts
  tests/unit/src/lib/frontend/components/__snapshots__/CategoryProducts.spec.ts.snap
  tests/unit/src/lib/frontend/components/__snapshots__/ProductCard.spec.ts.snap
  tests/unit/src/lib/frontend/components/__snapshots__/ShoppingCartProductCard.spec.ts.snap
Labels: bug

#69 Feat/ost 66 implement categories list modal
  src/lib/frontend/components/CategoryListModal.svelte
  src/lib/frontend/components/CustomAppBar.svelte
  src/lib/frontend/components/icons/CloseIcon.svelte
  src/lib/frontend/components/icons/GridIcon.svelte
  src/routes/+layout.svelte
  tailwind.config.ts
  tests/unit/src/lib/frontend/components/CategoryListModal.spec.ts
  tests/unit/src/lib/frontend/components/CustomAppBar.svelte.spec.ts
  tests/unit/src/lib/frontend/components/__snapshots__/CategoryListModal.spec.ts.snap
Labels: good first issue, enhancement, beautification
